name: profiling
channels:
  - conda-forge
dependencies:
  - python=3.9.1
  - pip=21.1.1
  - compilers=1.1.3
  - Cython=0.29.22
  - uvloop=0.15.2
  - ipython=7.21.0
  - jupyterlab=3.0.14
  - jupyter-server-proxy=3.0.2
  # - viztracer=0.12.2
  - bokeh=2.3.1
  - graphviz=2.40.1
  - matplotlib=3.3.4
  - seaborn=0.11.1
  - numpy=1.20.2
  - pandas=1.2.4
  - xarray=0.18.0
  - coiled=0.0.40
  - flake8=3.9.1
  - black=21.5b0
  - pip:
      - git+https://github.com/gjoseph92/distributed.git@0c9220bb9b26f19099e50a0a28af6e9c9903fe36 --install-option="--with-cython=profile"
      - git+https://github.com/dask/dask.git@main
      # - git+https://github.com/gjoseph92/scheduler-profilers.git  # TODO this conflicts with --install-option for distributed, using postBuild instead
      # - git+https://github.com/gjoseph92/dask-noop.git